ApprenticeshipWebApplication/Entities/Training.cs
namespace ApprenticeshipWebApplication.Entities
{
    public class Training
    {  public int trainingId { get; set; } 
        public string trainingName { get; set; }
        public Student student { get; set; }
        public string studentId  { get; set; }
        public TeamLeader teamLeader { get; set; }
        public string teamLeaderId { get; set; }
        public SchoolSupervisor schoolSupervisor { get; set; }
        public string schoolSupervisorId { get; set; }
        public DateTime startDate { get; set; }
        public DateTime endDate { get; set; }
        public List <Assignment> assignments { get; set; } //كم اسايمنت انجو وكم واحد ضايل
        public int? estimatedNumberOfTasks { get; set; } = 0;

        public List<TrainingObjectives> trainingObjectives { get; set; }



    }
}

ApprenticeshipWebApplication/Controllers/TrainingController.cs
using ApprenticeshipWebApplication.DTO;
using ApprenticeshipWebApplication.Entities;
using ApprenticeshipWebApplication.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace ApprenticeshipWebApplication.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class TrainingController : Controller
    {
        ITrainingRepository trainingRepository;
        IObjectiveRepository objectiveRepository;
        IStudentRepository studentRepository;
        ISchoolSupervisorRepository schoolSupervisorRepository;
        ITeamLeaderRepository teamLeaderRepository;
        public TrainingController(ITrainingRepository trainingRepository, IObjectiveRepository objectiveRepository, IStudentRepository studentRepository, ISchoolSupervisorRepository schoolSupervisorRepository, ITeamLeaderRepository teamLeaderRepository)
        {
            this.trainingRepository = trainingRepository;
            this.objectiveRepository = objectiveRepository;
            this.studentRepository = studentRepository;
            this.schoolSupervisorRepository = schoolSupervisorRepository;
            this.teamLeaderRepository = teamLeaderRepository;
        }

        public IActionResult Index()
        {
            ViewBag.trainings = trainingRepository.GetAllTrainings();
           
            return View();
        }

        public IActionResult Add()
        {
            ViewBag.objectives = objectiveRepository.GetAllObjectives();
            ViewBag.students = studentRepository.GetAllStudents();
            ViewBag.teamLeaders = teamLeaderRepository.GetAllTeamLeaders();
            ViewBag.schoolSupervisors =schoolSupervisorRepository.GetAllSchoolSupervisors();



            return View();
        }
        

        public async Task<IActionResult> Create(InsertTrainingDTO trainingDTO)
        {
            
                Training training = new Training();
                training.trainingName = trainingDTO.trainingName;
                training.studentId = trainingDTO.studentId;
                training.schoolSupervisorId = trainingDTO.schoolSupervisorId;
                training.teamLeaderId = trainingDTO.teamLeaderId;
                training.startDate = trainingDTO.startDate;
                training.endDate = trainingDTO.endDate;
                await trainingRepository.AddTraining(training, trainingDTO.objectiveIds);
                return RedirectToAction("Index");
            

        }

        public IActionResult Edit(int id)
         {
            var training = trainingRepository.GetTraining(id);

             UpdateTrainingDTO trainingDTO = new UpdateTrainingDTO();
             trainingDTO.id = training.trainingId;
             trainingDTO.trainingName = training.trainingName;
             trainingDTO.studentId=training.studentId;
             trainingDTO.schoolSupervisorId=training.schoolSupervisorId;
             trainingDTO.teamLeaderId=training.teamLeaderId;
             trainingDTO.startDate = training.startDate;
             trainingDTO.endDate = training.endDate;
             trainingDTO. objectiveIds = training.trainingObjectives.Select(x => x.objectiveId).ToList();

             ViewBag.objectives = objectiveRepository.GetAllObjectives();
             ViewBag.students = studentRepository.GetAllStudents();
             ViewBag.teamLeaders = teamLeaderRepository.GetAllTeamLeaders();
             ViewBag.schoolSupervisors = schoolSupervisorRepository.GetAllSchoolSupervisors();
             return View(trainingDTO);



         }
        public async Task<IActionResult> Update(UpdateTrainingDTO trainingDTO)
        {
            var training = trainingRepository.GetTraining(trainingDTO.id);

            if (training == null)
            {
                // Handle the case where training is not found, e.g., return a not found response
                return NotFound();
            }

            training.studentId = trainingDTO.studentId;
            training.trainingName = trainingDTO.trainingName;
            training.schoolSupervisorId = trainingDTO.schoolSupervisorId;
            training.teamLeaderId = trainingDTO.teamLeaderId;
            training.startDate = trainingDTO.startDate;
            training.endDate = trainingDTO.endDate;

            await trainingRepository.UpdateTraining(training, trainingDTO.objectiveIds);
            return RedirectToAction("Index");
        }


     
        public async Task<IActionResult> Delete(int id)
        {
            await trainingRepository.DeleteTraining(id);
            return RedirectToAction("Index");

        }
     
        }
}

ApprenticeshipWebApplication/Views/Training/Add.cshtml
@using ApprenticeshipWebApplication.DTO;
@using ApprenticeshipWebApplication.Entities
@model InsertTrainingDTO
<div class="container-fluid">
    <h2>Set a new Training .</h2>

<form action="/Training/Create">
    <!-- Add form fields for TrainingDTO properties -->
      <label for="trainingName">Training Name</label>
       <input asp-for="trainingName" class="form-control" type="text" />
        <label for="studentId">Select Student</label>
        <select name="studentId" class="form-control">
            @foreach (var student in (List<Student>)ViewBag.students)
            {
                <option value="@student.Id">@student.firstName @student.lastName</option>
            }
        </select>
    

        <label for="teamLeaderId">Select Team Leader</label>
        <select name="teamLeaderId" class="form-control">
            @foreach (var teamLeader in (List<TeamLeader>)ViewBag.teamLeaders)
            {
                <option value="@teamLeader.Id">@teamLeader.firstName @teamLeader.lastName</option>
            }
        </select>

        <label for="schoolSupervisorId">Select School Supervisor</label>
        <select name="schoolSupervisorId" class="form-control">
            @foreach (var schoolSupervisor in (List<SchoolSupervisor>)ViewBag.schoolSupervisors)
            {
                <option value="@schoolSupervisor.Id">@schoolSupervisor.firstName @schoolSupervisor.lastName</option>
            }
        </select>

        <label for="objectiveIds">Select Objectives</label>
        <select name="objectiveIds" class="form-control" multiple>
            @foreach (var objective in (List<Objective>)ViewBag.objectives)
            {
                <option value="@objective.objectiveId">@objective.objectiveName</option>
            }
        </select>
        <label for="startDate">Start Date</label>
        <input asp-for="startDate" class="form-control" type="date" />
        <label for="endDate">End Date</label>
         <input asp-for="endDate" class="form-control" type="date" />

    <button type="submit" class="w-100 btn btn-lg btn-primary">Create</button>
</form>
</div>

ApprenticeshipWebApplication/Views/Training/Edit.cshtml
@using ApprenticeshipWebApplication.DTO;
@using ApprenticeshipWebApplication.Entities
@model UpdateTrainingDTO
<div class="container-fluid">
    <h2>Edit Training Info.</h2>

<form asp-controller="Training" asp-action="Update" method="post">
    <input type="hidden" asp-for="id" />
    <label for="trainingName">Training Name</label>
    <input asp-for="trainingName" class="form-control" type="text" />
    <label for="studentId">Select Student</label>
    <select name="studentId" class="form-control">
       @foreach (var s in (List<Student>)ViewBag.students)
            {
                @if (Model.studentId == s.Id)
                {
                <option selected="selected" value="@s.Id">@s.firstName @s.secondName @s.thirdName @s.lastName</option>
            }
            else
            {
                <option value="@s.Id">@s.firstName @s.secondName @s.thirdName @s.lastName</option>

            }

            }
      

    </select>
  
    <label for="teamLeaderId">Select Team Leader</label>
    <select name="teamLeaderId" class="form-control">
        @foreach (var t in (List<TeamLeader>)ViewBag.teamLeaders)
        {  @if (Model.teamLeaderId == t.Id)
            {
                <option selected="selected" value="@t.Id">@t.firstName @t.secondName @t.thirdName @t.lastName</option>
            }
            else
            {
                <option value="@t.Id">@t.firstName @t.lastName</option>

            }
        }
    </select>

    <label for="schoolSupervisorId">Select School Supervisor</label>
    <select name="schoolSupervisorId" class="form-control">
        @foreach (var schoolSupervisor in (List<SchoolSupervisor>)ViewBag.schoolSupervisors)
        {    @if (Model.schoolSupervisorId == schoolSupervisor.Id)
            {
                <option selected="selected" value="@schoolSupervisor.Id">@schoolSupervisor.firstName @schoolSupervisor.secondName @schoolSupervisor.thirdName @schoolSupervisor.lastName</option>
            }
            else
            {
                <option value="@schoolSupervisor.Id">@schoolSupervisor.firstName @schoolSupervisor.lastName</option>


            }

        }
    </select>
    <label for="objectiveIds">Select Objectives</label>
    <select name="objectiveIds" class="form-control" multiple>
    @foreach (var objective in (List<Objective>)ViewBag.objectives)
    {
        @if (Model.objectiveIds.Contains(objective.objectiveId))
        {
            <option selected="selected" value="@objective.objectiveId">@objective.objectiveName</option>
        }
        else
        {
            <option value="@objective.objectiveId">@objective.objectiveName</option>
        }
    }
    </select>

    
    <label for="startDate">Start Date</label>
    <input asp-for="startDate" class="form-control" type="date" />
    <label for="endDate">End Date</label>
    <input asp-for="endDate" class="form-control" type="date" />

    <button type="submit" class="w-100 btn btn-lg btn-primary">Update</button>
</form>
</div>

ApprenticeshipWebApplication/Views/Training/Index.cshtml
@using ApprenticeshipWebApplication.Entities
<div class="container-fluid">

    <a class="btn btn-primary" href="/Training/Add">Set a new Training</a>
    <br />
    <br />

    <table class="table table-striped">
        <tr>
            <th>Training Name</th>
            <th>Student</th>
            <th>Team Leader</th>
            <th>School Supervisor</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Objectives</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        @foreach (var training in (List<Training>)ViewBag.trainings)
        {
                <tr>
                    <td>@training.trainingName</td>
                    <td>@training.student.firstName @training.student.lastName</td>
                    <td>@training.teamLeader.firstName @training.teamLeader.lastName</td>
                    <td>@training.schoolSupervisor.firstName @training.schoolSupervisor.lastName</td>
                    <td>@training.startDate.ToString("yyyy-MM-dd")</td>
                    <td>@training.endDate.ToString("yyyy-MM-dd")</td>
                    <td>
                    @foreach (var trainingObjective in training.trainingObjectives)
                    {
                                <div>@trainingObjective.objective.objectiveName</div>
                    }
                    </td>
                    <td><button type="button" class="btn btn-light"> <a href="/Training/Edit?id=@training.trainingId">Edit</a></button></td>
                    <td><button type="button" class="btn btn-danger"> <a href="/Training/Delete?id=@training.trainingId">Delete</a></button></td>
                </tr>
        }
    </table>
</div>